<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php if(@$data['name']): ?><?php echo e($data['name']); ?> - <?php endif; ?><?php echo e($site['title']); ?></title>
    <link rel="stylesheet" type="text/css" href="/styles/bundle.css">
  </head>
  <body class="view-<?php echo e($data['view']); ?>">
    <main class="container">
      <div class="pure-g">
        <div class="pure-u-1-6"></div>
        <div class="pure-u-5-6">
          <h2>
            <a href="<?php echo e($site['link']); ?>">
              <?php echo e($site['title']); ?>

            </a>
          </h2>

          <?php if(@$data['name']): ?><h1><?php echo e($data['name']); ?></h1><?php endif; ?>
        </div>
      </div>

      <?php echo $__env->yieldContent('content'); ?>

      <footer>
        Generated by <a href="https://11ty.dev">eleventy</a> at <time>XXX</time>.
      </footer>
    </main>
    <script src="/scripts/bundle.js"></script>
    <script src="//localhost:35729/livereload.js"></script>
  </body>
</html>
<?php /**PATH /mnt/files/Desktop/datashaman/tongs/resources/views/default.blade.php ENDPATH**/ ?>